{
 "title": "IoT Pipeline Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Flink Processing Throughput (Records/Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_numRecordsOut[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Partition Max Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL WAL Write Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_replication_wal_write_lag",
     "legendFormat": "WAL Write Lag (Bytes)"
    }
   ]
  }
 ]
}