{
 "title": "IoT Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Raw Records Flink is Behind Kafka",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max)",
     "legendFormat": "{{instance}} p{{partition}}"
    }
   ]
  },
  {
   "title": "Flink: Records Written to Enriched Data Topic per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(host) (rate(flink_taskmanager_job_task_operator_KafkaProducer_record_send_total[1m]))",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Records Written to raw_metrics Topic per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_topic_metrics_record_send_total{topic=\"postgres.public.raw_metrics\"}[1m])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Records Received by Debezium per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(debezium_postgres_connector_metrics_totalnumberofeventsseen{context=\"streaming\"}[1m])",
     "legendFormat": "Debezium events/min"
    }
   ]
  },
  {
   "title": "Records Written to Postgres per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"iotdb\"}[1m])",
     "legendFormat": "Postgres inserts/min"
    }
   ]
  },
  {
   "title": "WAL Lag in Bytes from IotDB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_replication_slots_pg_wal_lsn_diff{database=\"iotdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Debezium Records Produced per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_record_send_total{instance=\"connect:8090\", client_id=\"connector-producer-raw-metrics-connector-0\"}[1m])",
     "legendFormat": "Debezium produced/min"
    }
   ]
  },
  {
   "title": "Records Processed Per Minutes in Flink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_total[1m]))",
     "legendFormat": "{{instance}} p{{partition}}"
    }
   ]
  },
  {
   "title": "Lag: Postgres to Debezium",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile(0.1, debezium_postgres_connector_metrics_millisecondsbehindsource{context=\"streaming\"})",
     "legendFormat": "Debezium Behind Source - p10 (ms)"
    },
    {
     "expr": "quantile(0.5, debezium_postgres_connector_metrics_millisecondsbehindsource{context=\"streaming\"})",
     "legendFormat": "Debezium Behind Source - p50 (ms)"
    },
    {
     "expr": "quantile(0.9, debezium_postgres_connector_metrics_millisecondsbehindsource{context=\"streaming\"})",
     "legendFormat": "Debezium Behind Source - p90 (ms)"
    }
   ]
  },
  {
   "title": "Lag: End-to-End to Flink (Event Time Lag)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile(0.1, flink_taskmanager_job_task_operator_currentEmitEventTimeLag)",
     "legendFormat": "Flink Event Time Lag - p10 (ms)"
    },
    {
     "expr": "quantile(0.5, flink_taskmanager_job_task_operator_currentEmitEventTimeLag)",
     "legendFormat": "Flink Event Time Lag - p50 (ms)"
    },
    {
     "expr": "quantile(0.9, flink_taskmanager_job_task_operator_currentEmitEventTimeLag)",
     "legendFormat": "Flink Event Time Lag - p90 (ms)"
    }
   ]
  },
  {
   "title": "Lag: Flink Sink to Kafka (Request Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile(0.1, flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg)",
     "legendFormat": "Flink Kafka Sink Latency - p10 (ms)"
    },
    {
     "expr": "quantile(0.5, flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg)",
     "legendFormat": "Flink Kafka Sink Latency - p50 (ms)"
    },
    {
     "expr": "quantile(0.9, flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg)",
     "legendFormat": "Flink Kafka Sink Latency - p90 (ms)"
    }
   ]
  }
 ]
}